# Generated by Django 3.0.6 on 2020-06-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_description',
            field=models.TextField(default=''),
        ),
    ]
