# Generated by Django 3.0.6 on 2020-06-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20200602_1246'),
        ('jedzonko', '0002_auto_20200602_1311'),
    ]

    operations = [
    ]
